var rn = require("./romanNumerals");

console.log(rn.toRoman(1) === 'I');          
console.log(rn.toRoman(3) === 'III');        
console.log(rn.toRoman(4) === 'IV');         
console.log(rn.toRoman(12) === 'XII');       
console.log(rn.toRoman(23) === 'XXIII');
console.log(rn.toRoman(37) === 'XXXVII');
console.log(rn.toRoman(45) === 'XLV');       
console.log(rn.toRoman(56) === 'LVI');       
console.log(rn.toRoman(69) === 'LXIX');      
console.log(rn.toRoman(74) === 'LXXIV');
console.log(rn.toRoman(82) === 'LXXXII');
console.log(rn.toRoman(96) === 'XCVI');      
console.log(rn.toRoman(102) === 'CII');      
console.log(rn.toRoman(114) === 'CXIV');     
console.log(rn.toRoman(127) === 'CXXVII');
console.log(rn.toRoman(138) === 'CXXXVIII');
console.log(rn.toRoman(144) === 'CXLIV');    
console.log(rn.toRoman(202) === 'CCII');
console.log(rn.toRoman(303) === 'CCCIII');
console.log(rn.toRoman(404) === 'CDIV');     
console.log(rn.toRoman(999) === 'CMXCIX');   
console.log(rn.toRoman(1000) === 'M');
console.log(rn.toRoman(2000) === 'MM');
console.log(rn.toRoman(3000) === 'MMM');
console.log(rn.toRoman(3999) === 'MMMCMXCIX');